// app/network/endpoints.ts
export const endpoints = {
//   getUser: (id: string) => `/users/${id}`,
  getUser:'/user',
  sigin:'/signin',
  signup:'/signUp',
  expenses: '/expenses',
  expense: (id: string) => `/expenses/${id}`,
  budgets: '/budgets',
  budget: (id: string) => `/budgets/${id}`,
  budgetStatus: (id: string) => `/budgets/${id}/status`,
  budgetsWithStatus: '/budgets/with-status',
  notifications: '/notifications',
  notification: (id: string) => `/notifications/${id}`,
  notificationUnreadCount: '/notifications/unread-count',
  markNotificationRead: (id: string) => `/notifications/${id}/read`,
  markAllNotificationsRead: '/notifications/mark-all-read',
  deleteAllReadNotifications: '/notifications/read/all',
  createTestNotification: '/notifications/test',
};